name: Daily Node JS Learnings
on:
  schedule:
    - cron: 00 07 * * *

jobs:
  create_issue:
    name: Create an issue to track my NodeJS learning
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create an issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "rufilboy"
          labels: "daily sync, node-learnings"
          title: "Daily sync"
          body: |
            ### Agenda

            - [ ] Learn with consistence!
            - [ ] Write down what you've learnt TODAY!
            - [ ] Did you learn any new things today?
            - [ ] Did you meet any techie learning Node JS as you are?
                    
            ### Points
            Add things you must finished learning tomorrow

            - [Continue your learning here](https://www.youtube.com/playlist?list=PLC3y8-rFHvwh8shCMHFA5kWxD9PaPwxaY)
          pinned: false
          close-previous: false
          token: ${{ secrets.DAILY_GITHUB_TOKEN }}
          